// src/views/Popup.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { t } from "@/shared/i18n.svelte";
  import { GAME_HOST } from "@/shared/constants";
  import Main from "@/views/Main.svelte";
  import Settings from "@/views/Settings.svelte";
  import Notice from "@/views/Notice.svelte";
  import { appStore } from "@/shared/store.svelte";
  import { View } from "@/shared/types";
  let ready = $state(false);
  let warnMsg = $state("");
  let errorMsg = $state("");

  async function getGameTab(): Promise<chrome.tabs.Tab | null> {
    const [tab] = await chrome.tabs.query({
      active: true,
      currentWindow: true,
    });
    return tab?.url?.includes(GAME_HOST) ? tab : null;
  }


  onMount(async () => {
    await appStore.init();

    const isTabMode = new URLSearchParams(window.location.search).get("mode") === "tab";
    if (isTabMode) {
      document.body.classList.add("tab-mode");
      const tabs = await chrome.tabs.query({ url: `*://${GAME_HOST}/*` });
      if (tabs.length === 0) {
        warnMsg = t("not_game_page_body");
      }
      ready = true;
      return;
    }

    const tab = await getGameTab();
    if (!tab) {
      warnMsg = t("not_game_page_body");
      ready = true;
      return;
    }

    ready = true;
  });
</script>

{#if ready}
  {#if appStore.view === View.Settings}
    <Settings />
  {:else if warnMsg || errorMsg}
    <Notice {warnMsg} {errorMsg} />
  {:else}
    <Main />
  {/if}
{/if}

// src/views/Popup.tsx
import { type Component, createSignal, Match, onMount, Switch } from "solid-js";
import { t } from "@/shared/i18n.ts";
import { GAME_HOST } from "@/shared/constants.ts";
import Main from "@/views/Main.tsx";
import Settings from "@/views/Settings.tsx";
import Notice from "@/views/Notice.tsx";
import { appStore, appStoreActions } from "@/shared/store.ts";
import { View } from "@/shared/types.ts";

export const Popup: Component = () => {
  const [ready, setReady] = createSignal(false);
  const [warnMsg, setWarnMsg] = createSignal("");
  const [errorMsg] = createSignal("");

  async function getGameTab(): Promise<chrome.tabs.Tab | null> {
    const [tab] = await chrome.tabs.query({
      active: true,
      currentWindow: true,
    });
    return tab?.url?.includes(GAME_HOST) ? tab : null;
  }

  onMount(async () => {
    await appStoreActions.init();

    const isTabMode =
      new URLSearchParams(window.location.search).get("mode") === "tab";
    if (isTabMode) {
      document.body.classList.add("tab-mode");
      const tabs = await chrome.tabs.query({ url: `*://${GAME_HOST}/*` });
      if (tabs.length === 0) {
        setWarnMsg(t("not_game_page_body"));
      }
      setReady(true);
      return;
    }

    const tab = await getGameTab();
    if (!tab) {
      setWarnMsg(t("not_game_page_body"));
      setReady(true);
      return;
    }

    setReady(true);
  });

  return (
    <Switch>
      <Match when={!ready()}>
        {/* Empty or loading spinner during initialization */}
        <div style="display: flex; align-items: center; justify-content: center; min-height: 200px; color: var(--text-dim);">
          Loading...
        </div>
      </Match>
      <Match when={appStore.view === View.Settings}>
        <Settings />
      </Match>
      <Match when={warnMsg() || errorMsg()}>
        <Notice warnMsg={warnMsg()} errorMsg={errorMsg()} />
      </Match>
      <Match when={true}>
        <Main />
      </Match>
    </Switch>
  );
};

export default Popup;
